cses problem url support added
Rishabh-malhotraa/caucus pull request #55
Opened 2021-10-06 08:16 UTC by starkkumarkk1611

I have solved issue #52 
Please review my code and merge it.
If any Improvement is needed please suggest and guide me.
# thanks, I would like to work on more issues like this.

2021-10-17 11:14 UTC, nabi-ebrahimi requested changes
Please consider a new candition  in the CodeForces.tsx  for  **cses.fi**  as well.


` <div>
      {hostname === "codeforces.com" ? (
        <div className={"codeforces"} ref={MathRef}>
          {parse(htmlString)}
        </div>
      ) : (
        <div className={"atcoder"} ref={MathRef}>
          {parse(htmlString)}
        </div>
      )}
      <Divider />
    </div>`

2021-10-19 12:59 UTC, 0xbacklit reviewed
Thanks, I just forgot to remove my earlier javascript that was not working. 
Now I have removed It and deleted unwanted white space also

2021-10-19 13:23 UTC, starkkumarkk1611 commented
> > Please consider a new candition in the CodeForces.tsx for **cses.fi** as well.
> > ` <div> {hostname === "codeforces.com" ? ( <div className={"codeforces"} ref={MathRef}> {parse(htmlString)} </div> ) : ( <div className={"atcoder"} ref={MathRef}> {parse(htmlString)} </div> )} <Divider /> </div>`
> 
> please consider these changes as well

thanks, just now I am doing sir

2021-10-20 09:21 UTC, nabi-ebrahimi requested changes

2026-03-09 21:04 UTC, closed without merging